services:
  - type: web
    name: mibyou-salon-diagnosis
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: "18"
    headers:
      - path: "/*"
        name: "X-Frame-Options"
        value: "DENY"
      - path: "/*"
        name: "X-Content-Type-Options"
        value: "nosniff"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"